import type { Metadata } from "next"
import { Geist_Mono, Inter } from "next/font/google"
import { Toaster } from "@/components/ui/sonner"
import { ThemeProvider } from "@/components/theme-provider"
import "./globals.css"
import { Analytics } from "@vercel/analytics/next"
import { SpeedInsights } from "@vercel/speed-insights/next"

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
  display: 'swap',
  preload: true,
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: 'swap',
})

const BASE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://taophim.com'

export const metadata: Metadata = {
  // Basic metadata
  title: {
    default: "Taophim - Ghép Mặt AI & Tạo Video AI Chuyên Nghiệp | Giá Rẻ #1 Việt Nam",
    template: "%s | Taophim - Video AI Việt Nam",
  },
  description: "Dịch vụ ghép mặt AI (Face Swap), tạo video từ ảnh chất lượng 4K tại Việt Nam. Không cần kỹ năng, không cần thẻ quốc tế. Thanh toán VietQR, nhận video trong vài giờ. Tiết kiệm 90% chi phí so với thuê editor.",
  keywords: [
    // Primary keywords - High intent
    "ghép mặt AI",
    "face swap AI",
    "dịch vụ ghép mặt",
    "ghép mặt video",
    "tạo video AI",
    "video AI Việt Nam",
    // Service-specific
    "ghép mặt TikTok",
    "ghép mặt Reels",
    "tạo video từ ảnh",
    "ảnh thành video",
    "image to video AI",
    "text to video tiếng Việt",
    // Benefit keywords
    "làm video không cần kỹ năng",
    "tạo video giá rẻ",
    "video marketing AI",
    // Brand + location
    "Taophim",
    "taophim.com",
    "công cụ video AI Việt Nam",
    // Long-tail
    "ghép mặt vào video có sẵn",
    "tạo video bán hàng AI",
    "video quảng cáo AI",
    "content creator tool Vietnam",
  ],
  authors: [{ name: "Taophim" }],
  creator: "Taophim",
  publisher: "Taophim",
  
  // Favicon and icons
  icons: {
    icon: [
      { url: "/favicon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/icon.png", sizes: "192x192", type: "image/png" },
    ],
    apple: [
      { url: "/apple-icon.png", sizes: "180x180", type: "image/png" },
    ],
    shortcut: "/favicon-32.png",
  },
  manifest: "/site.webmanifest",
  
  // Canonical URL
  metadataBase: new URL(BASE_URL),
  alternates: {
    canonical: "/",
    languages: {
      "vi-VN": "/",
    },
  },
  
  // OpenGraph metadata for social sharing
  // Note: OG image is auto-generated by /src/app/opengraph-image.tsx
  openGraph: {
    type: "website",
    locale: "vi_VN",
    url: BASE_URL,
    siteName: "Taophim",
    title: "Ghép Mặt AI & Tạo Video Chuyên Nghiệp | Taophim.com",
    description: "Biến ảnh của bạn thành video viral chỉ trong vài giờ. Dịch vụ ghép mặt AI, tạo video từ ảnh chất lượng 4K. Thanh toán VietQR, không cần thẻ quốc tế.",
  },

  // Twitter Card metadata
  // Note: Twitter image is auto-generated by /src/app/twitter-image.tsx (fallback to opengraph-image)
  twitter: {
    card: "summary_large_image",
    title: "Ghép Mặt AI & Tạo Video Chuyên Nghiệp | Taophim",
    description: "Biến ảnh thành video viral chất lượng 4K. Ghép mặt AI, tạo video từ ảnh. Thanh toán VietQR, nhận video trong vài giờ.",
    creator: "@taophim",
  },
  
  // Robots directives
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  
  // Verification
  verification: {
    google: "p70tZR-mTP2SwExwu8egoBzuaa_G2VdmT3I-nGtuOng",
  },
  
  // App-specific metadata
  applicationName: "Taophim",
  category: "technology",
  classification: "AI Video Generation Platform",

  // Mobile optimization
  formatDetection: {
    telephone: false,
  },

  // Other metadata
  other: {
    "mobile-web-app-capable": "yes",
    "apple-mobile-web-app-capable": "yes",
    "apple-mobile-web-app-status-bar-style": "black-translucent",
  },
}

// JSON-LD structured data for SEO
const jsonLd = {
  "@context": "https://schema.org",
  "@type": "WebApplication",
  "name": "Taophim",
  "alternateName": ["Taophim.com", "Tạo Phim AI", "Ghép Mặt AI Việt Nam"],
  "description": "Dịch vụ ghép mặt AI (Face Swap) và tạo video từ ảnh chất lượng 4K tại Việt Nam. Không cần kỹ năng, thanh toán VietQR, nhận video trong vài giờ.",
  "url": "https://taophim.com",
  "applicationCategory": "MultimediaApplication",
  "operatingSystem": "Web",
  "offers": {
    "@type": "Offer",
    "price": "0",
    "priceCurrency": "VND",
    "description": "Đăng ký miễn phí, chỉ trả phí khi sử dụng dịch vụ"
  },
  "aggregateRating": {
    "@type": "AggregateRating",
    "ratingValue": "5.0",
    "reviewCount": "1000",
    "bestRating": "5",
    "worstRating": "1"
  },
  "provider": {
    "@type": "Organization",
    "name": "Taophim",
    "url": "https://taophim.com",
    "logo": "https://taophim.com/logo.png"
  },
  "featureList": [
    "Ghép mặt AI (Face Swap)",
    "Tạo video từ ảnh (Image to Video)",
    "Video chất lượng 4K",
    "Thanh toán VietQR",
    "Không cần thẻ quốc tế"
  ],
  "inLanguage": "vi-VN",
  "audience": {
    "@type": "Audience",
    "audienceType": "Content Creators, Marketers, Business Owners"
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="vi" className={`${inter.variable} dark`} suppressHydrationWarning>
      <head>
        <meta name="theme-color" content="#09090b" />
        <link
          rel="preload"
          href="/images/landing/long-form-bg.webp"
          as="image"
          type="image/webp"
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body
        className={`${geistMono.variable} antialiased min-h-screen bg-background`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          forcedTheme="dark"
          disableTransitionOnChange
        >
          {children}
          <Toaster richColors position="top-center" />
          <Analytics />
          <SpeedInsights />
        </ThemeProvider>
      </body>
    </html>
  )
}
